server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:file:~/Sachin/learning/ratingdb
    username: sa
    password: pass
    driver-class-name: org.h2.Driver
  application:
    name: RATING-SERVICE

  h2:
    console:
      enabled: true
      # path: /h2-console

  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka